input {
  file {
    path => "/home/g4/streamlit/*.csv"
    start_position => "beginning"
    # Usamos /dev/null para que siempre re-lea los archivos al reiniciar logstash (útil para pruebas)
    sincedb_path => "/dev/null"
    mode => "read"
    exit_after_read => true 
  }
}

filter {
  csv {
    separator => ","
    skip_header => "true"
    columns => ["id","title","original_title","release_date","overview","popularity","vote_average","vote_count","runtime","poster_url","genre_names","director","cast_names","cast_images_urls"]
    quote_char => '"' 
  }

  mutate {
    convert => {
      "popularity" => "float"
      "vote_average" => "float"
      "vote_count" => "integer"
      "runtime" => "integer"
    }
  }

  date {
    match => ["release_date", "yyyy-MM-dd", "dd/MM/yyyy"]
    target => "release_date"
    tag_on_failure => ["_dateparsefailure"] 
  }

  # --- TRANSFORMACIONES DE DATOS ---
  if [genre_names] {
    mutate { split => { "genre_names" => ", " } }
  }
  
  if [cast_names] {
    mutate { split => { "cast_names" => ", " } }
  }
  
  if [cast_images_urls] {
    mutate { split => { "cast_images_urls" => " | " } }
  }
  
  mutate {
    strip => ["title", "original_title", "director", "poster_url"]
  }

  # --- LIMPIEZA DE METADATOS ---
  # Vital para evitar errores si tienes mapping strict
  mutate {
    remove_field => ["host", "event", "log", "message", "@version", "@timestamp"]
  }
}

output {
  elasticsearch {
    # --- CAMBIO: SOLO UN NODO LOCAL ---
    hosts => ["https://127.0.0.1:9200"]
    
    # o usar user/password temporalmente.
    api_key => "_gMUxZoBGvoQi422JglW:1nPxPE86T3mJmqmMZ09vAQ" 
    
    ssl_enabled => true
    
    # Verifica que este archivo existe en tu máquina
    ssl_certificate_authorities => ["/home/g4/logstash-9.2.0/config/http_ca.crt"]
    ssl_verification_mode => "none"
    
    index => "peliculas-csv"
    document_id => "%{id}"
  }
  
  # Ver progreso (puntos) en la terminal
  stdout { codec => dots }
}
