input {
  file {
    path => "/home/g4/streamlit/peliculas*.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
    exit_after_read => true 
  }
}

filter {
  csv {
    separator => ","
    skip_header => "true"
    columns => ["id","title","original_title","release_date","overview","popularity","vote_average","vote_count","runtime","poster_url","genre_names","director","cast_names","cast_images_urls"]
    quote_char => '"' 
  }

  mutate {
    convert => {
      "popularity" => "float"
      "vote_average" => "float"
      "vote_count" => "integer"
      "runtime" => "integer"
    }
  }

  date {
    match => ["release_date", "yyyy-MM-dd", "dd/MM/yyyy"]
    target => "release_date"
    tag_on_failure => ["_dateparsefailure"] 
  }

  # --- TRANSFORMACIONES DE DATOS ---
  if [genre_names] {
    mutate { split => { "genre_names" => ", " } }
  }
  
  if [cast_names] {
    mutate { split => { "cast_names" => ", " } }
  }
  
  if [cast_images_urls] {
    mutate { split => { "cast_images_urls" => " | " } }
  }
  
  mutate {
    strip => ["title", "original_title", "director", "poster_url"]
  }

  # --- [NUEVO] LIMPIEZA DE METADATOS ---
  # Eliminamos los campos que Logstash añade automáticamente
  # para que no choquen con el modo 'strict' de Elasticsearch.
  mutate {
    remove_field => ["host", "event", "log", "message", "@version", "@timestamp"]
  }
}

output {
  elasticsearch {
    hosts => ["https://192.199.1.38:9200", "https://192.199.1.40:9200", "https://192.199.1.54:9200"]
    
    # --- CAMBIO DE SEGURIDAD ---
    # Borra user y password
    # Pega aquí el ID y la KEY que te dio Kibana separados por ":"
    api_key => "_gMUxZoBGvoQi422JglW:1nPxPE86T3mJmqmMZ09vAQ" 
    
    ssl_enabled => true
    ssl_certificate_authorities => ["/home/g4/logstash-9.2.0/config/http_ca.crt"]
    ssl_verification_mode => "none"
    
    index => "peliculas-csv"
    document_id => "%{id}"
  }
  stdout { codec => dots }
}