input {
  file {
    path => "/home/g4/streamlit/peliculas_nuevas_*.csv"
    sincedb_path => "/home/g4/logstash-9.2.0/data/sincedb_scrapping" 
    start_position => "beginning"
    mode => "read"
  }
}

filter {
  csv {
    separator => ","
    skip_header => "true"
    columns => ["id","title","original_title","release_date","overview","popularity","vote_average","vote_count","runtime","poster_url","genre_names","director","cast_names","cast_images_urls"]
    quote_char => '"'
  }

  # --- REQUISITO: GROK ---
  if [release_date] {
    grok {
      match => { "release_date" => "^%{YEAR:anio}-%{MONTHNUM:mes}-%{MONTHDAY:dia}" }
    }
  }

  mutate {
    convert => { "popularity" => "float" "vote_average" => "float" "runtime" => "integer" }
    strip => ["title", "original_title"]
    remove_field => ["host", "event", "log", "message", "@version"]
  }

  if [genre_names] { mutate { split => { "genre_names" => ", " } } }
  if [cast_names] { mutate { split => { "cast_names" => ", " } } }
  
  date {
    match => ["release_date", "yyyy-MM-dd"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["https://192.199.1.38:9200", "https://192.199.1.40:9200", "https://192.199.1.54:9200"]
    api_key => "TU_ID:TU_API_KEY" 
    ssl_enabled => true
    ssl_verification_mode => "none"
    ssl_certificate_authorities => ["/home/g4/logstash-9.2.0/config/http_ca.crt"]

    # --- REQUISITO: ÍNDICE DINÁMICO ---
    index => "log-scrapping-%{+YYYY.MM.dd}"
    document_id => "%{id}"
    doc_as_upsert => true
  }
}